### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by matze** [ufo-kit/concert#137]
This is a meta issue to discuss what needs to be done for a 1.0 release of Concert. Feel free to add more here.
### Features

Should we use [any](http://www.gevent.org/) [of](https://code.google.com/p/tulip/) [the](http://eventlet.net/) [many](http://twistedmatrix.com/trac/) single-threaded async frameworks instead of the `ThreadPoolExecutor`? AFAICT, we face spurious problems when a lot is going on and the number of pre-set threads is reached. We can always increase that number, but this is definitely not a long-term solution.

**This has been solved.**
### Issues
- [x] State machines or not: #95
- [x] Lab model: #118 
- [ ] Consistent usage of `@async`: #136 
- [x] Unit conversion: #138 
- [x] Remove facility-specific code: #139 
- [x] Function/generator naming #147 
- [x] Camera abstractions #148
